version: "3"
networks:
  rentstream_net:
volumes:
  dbdata:
services:
  gateway:
    networks:
      - rentstream_net
    build:
      context: ./gateway
    ports:
      - 8080:8080
      - 9876:9876

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "dbdata:/data/db"
    networks:
      - rentstream_net

  users:
    networks:
      - rentstream_net
    build:
      context: ./service-users
    depends_on: 
      - database

  catalog:
    networks:
      - rentstream_net
    build:
      context: ./service-catalog
    depends_on: 
      - database

  renting:
    networks:
      - rentstream_net
    build:
      context: ./service-renting
    depends_on: 
      - database
  
  streaming:
    networks:
      - rentstream_net
    build:
      context: ./service-streaming