version: "3"
networks:
  rentstream_net:
    external: true
volumes:
  dbdata:
services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "dbdata:/data/db"
    networks:
      - rentstream_net

  users:
    networks:
      - rentstream_net
    build:
      context: ./service-users
    depends_on: 
      - database
    ports:
      - 7051:3000

  catalog:
    networks:
      - rentstream_net
    build:
      context: ./service-catalog
    depends_on: 
      - database
    ports:
      - 7052:3000

  renting:
    networks:
      - rentstream_net
    build:
      context: ./service-renting
    depends_on: 
      - database
    ports:
      - 7053:3000