version: "3"
networks:
  rentstream_net:
    external: true
services:
  users:
    networks:
      - rentstream_net
    build:
      context: ./service-users
    ports:
      - 7051:3000
  catalog:
    networks:
      - rentstream_net
    build:
      context: ./service-catalog
    ports:
      - 7052:3000